apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-curl
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-curl
      #annotations:
        #iam.amazonaws.com/role: kubernetes/teamname/kube2iam-teamname-appname
    spec:
      containers:
        - name: docker-curl
          image: kenichishibata/docker-curl
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
